package entity;
// Generated 25.12.2017 23:50:41 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private Long id;
     private String fio;
     private Date birthday;
     private Book book;

    public Author() {
    }

	
    public Author(String fio, Date birthday) {
        this.fio = fio;
        this.birthday = birthday;
    }
    public Author(String fio, Date birthday, Book book) {
       this.fio = fio;
       this.birthday = birthday;
       this.book = book;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getFio() {
        return this.fio;
    }
    
    public void setFio(String fio) {
        this.fio = fio;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }




}


