package entity;
// Generated 25.12.2017 23:50:41 by Hibernate Tools 4.3.1



/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Long id;
     private Author author;
     private Genre genre;
     private Publisher publisher;
     private String name;
     private byte[] content;
     private int pageCount;
     private String isbn;
     private long genreId;
     private long authorId;
     private int publisherYear;
     private long publisherId;
     private byte[] image;

    public Book() {
    }

    public Book(Author author, Genre genre, Publisher publisher, String name, byte[] content, int pageCount, String isbn, long genreId, long authorId, int publisherYear, long publisherId, byte[] image) {
       this.author = author;
       this.genre = genre;
       this.publisher = publisher;
       this.name = name;
       this.content = content;
       this.pageCount = pageCount;
       this.isbn = isbn;
       this.genreId = genreId;
       this.authorId = authorId;
       this.publisherYear = publisherYear;
       this.publisherId = publisherId;
       this.image = image;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Author getAuthor() {
        return this.author;
    }
    
    public void setAuthor(Author author) {
        this.author = author;
    }
    public Genre getGenre() {
        return this.genre;
    }
    
    public void setGenre(Genre genre) {
        this.genre = genre;
    }
    public Publisher getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(Publisher publisher) {
        this.publisher = publisher;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getContent() {
        return this.content;
    }
    
    public void setContent(byte[] content) {
        this.content = content;
    }
    public int getPageCount() {
        return this.pageCount;
    }
    
    public void setPageCount(int pageCount) {
        this.pageCount = pageCount;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public long getGenreId() {
        return this.genreId;
    }
    
    public void setGenreId(long genreId) {
        this.genreId = genreId;
    }
    public long getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(long authorId) {
        this.authorId = authorId;
    }
    public int getPublisherYear() {
        return this.publisherYear;
    }
    
    public void setPublisherYear(int publisherYear) {
        this.publisherYear = publisherYear;
    }
    public long getPublisherId() {
        return this.publisherId;
    }
    
    public void setPublisherId(long publisherId) {
        this.publisherId = publisherId;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


