package entity;
// Generated 25.12.2017 23:50:41 by Hibernate Tools 4.3.1



/**
 * Publisher generated by hbm2java
 */
public class Publisher  implements java.io.Serializable {


     private Long id;
     private String name;
     private Book book;

    public Publisher() {
    }

	
    public Publisher(String name) {
        this.name = name;
    }
    public Publisher(String name, Book book) {
       this.name = name;
       this.book = book;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }




}


